/*
 * Camunda Rest API
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;
import io.swagger.client.model.ApproverGroups;
import io.swagger.client.model.Creditor;
import io.swagger.client.model.InvoiceCategory;
import io.swagger.client.model.InvoiceNumber;
import java.io.IOException;

/**
 * Variables
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-19T16:24:09.162Z")
public class Variables {
  @SerializedName("invoiceNumber")
  private InvoiceNumber invoiceNumber = null;

  @SerializedName("amount")
  private Amount amount = null;

  @SerializedName("creditor")
  private Creditor creditor = null;

  @SerializedName("invoiceCategory")
  private InvoiceCategory invoiceCategory = null;

  @SerializedName("approverGroups")
  private ApproverGroups approverGroups = null;

  public Variables invoiceNumber(InvoiceNumber invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Get invoiceNumber
   * @return invoiceNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public InvoiceNumber getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(InvoiceNumber invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public Variables amount(Amount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  public Amount getAmount() {
    return amount;
  }

  public void setAmount(Amount amount) {
    this.amount = amount;
  }

  public Variables creditor(Creditor creditor) {
    this.creditor = creditor;
    return this;
  }

   /**
   * Get creditor
   * @return creditor
  **/
  @ApiModelProperty(required = true, value = "")
  public Creditor getCreditor() {
    return creditor;
  }

  public void setCreditor(Creditor creditor) {
    this.creditor = creditor;
  }

  public Variables invoiceCategory(InvoiceCategory invoiceCategory) {
    this.invoiceCategory = invoiceCategory;
    return this;
  }

   /**
   * Get invoiceCategory
   * @return invoiceCategory
  **/
  @ApiModelProperty(required = true, value = "")
  public InvoiceCategory getInvoiceCategory() {
    return invoiceCategory;
  }

  public void setInvoiceCategory(InvoiceCategory invoiceCategory) {
    this.invoiceCategory = invoiceCategory;
  }

  public Variables approverGroups(ApproverGroups approverGroups) {
    this.approverGroups = approverGroups;
    return this;
  }

   /**
   * Get approverGroups
   * @return approverGroups
  **/
  @ApiModelProperty(required = true, value = "")
  public ApproverGroups getApproverGroups() {
    return approverGroups;
  }

  public void setApproverGroups(ApproverGroups approverGroups) {
    this.approverGroups = approverGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Variables variables = (Variables) o;
    return Objects.equals(this.invoiceNumber, variables.invoiceNumber) &&
        Objects.equals(this.amount, variables.amount) &&
        Objects.equals(this.creditor, variables.creditor) &&
        Objects.equals(this.invoiceCategory, variables.invoiceCategory) &&
        Objects.equals(this.approverGroups, variables.approverGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceNumber, amount, creditor, invoiceCategory, approverGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Variables {\n");
    
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    creditor: ").append(toIndentedString(creditor)).append("\n");
    sb.append("    invoiceCategory: ").append(toIndentedString(invoiceCategory)).append("\n");
    sb.append("    approverGroups: ").append(toIndentedString(approverGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

