/*
 * Camunda Rest API
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeploymentApi
 */
@Ignore
public class DeploymentApiTest {

    private final DeploymentApi api = new DeploymentApi();

    
    /**
     * Deployment051e15ae99b411e792b20242ac110002Get
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deploymentByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.deploymentByIdGet(accept, id);

        // TODO: test validations
    }
    
    /**
     * DeploymentCreatePost
     *
     * Create a Camunda Deployment.  Update the Deployment Name and Key/Value of the .bpmn file in the Body.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deploymentCreatePostTest() throws ApiException {
        String accept = null;
        String deploymentName = null;
        Boolean enableDuplicateFiltering = null;
        Boolean deployChangedOnly = null;
        String payTaxesBpmn = null;
        String smsBodyJs = null;
        api.deploymentCreatePost(accept, deploymentName, enableDuplicateFiltering, deployChangedOnly, payTaxesBpmn, smsBodyJs);

        // TODO: test validations
    }
    
    /**
     * DeploymentGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deploymentGetTest() throws ApiException {
        String accept = null;
        api.deploymentGet(accept);

        // TODO: test validations
    }
    
    /**
     * ProcessInstance3fde771b9aed11e792b20242ac110002Get
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processInstanceByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processInstanceByIdGet(accept, id);

        // TODO: test validations
    }
    
    /**
     * ProcessInstanceGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processInstanceGetTest() throws ApiException {
        String accept = null;
        api.processInstanceGet(accept);

        // TODO: test validations
    }
    
}
