/*
 * Camunda Rest API
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Model1group1createrequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * Group8454c987Cbc54a24Ba1aD420283caabdGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupByIdGetTest() throws ApiException {
        String id = null;
        api.groupByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * GroupCreatePost
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupCreatePostTest() throws ApiException {
        String accept = null;
        String contentType = null;
        Model1group1createrequest body = null;
        api.groupCreatePost(accept, contentType, body);

        // TODO: test validations
    }
    
    /**
     * GroupGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupGetTest() throws ApiException {
        api.groupGet();

        // TODO: test validations
    }
    
}
