/*
 * Camunda Rest API
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Model1processDefinition1key17Bkey7D1startRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessDefinitionApi
 */
@Ignore
public class ProcessDefinitionApiTest {

    private final ProcessDefinitionApi api = new ProcessDefinitionApi();

    
    /**
     * ProcessDefinitionPayTaxes1608cd76b9e4e11e7B8b70242ac110002Delete
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionByIdDeleteTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processDefinitionByIdDelete(accept, id);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionPayTaxes50520118099b411e792b20242ac110002StatisticsGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processDefinitionByIdGet(accept, id);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionPayTaxes50520118099b411e792b20242ac110002DiagramGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionDiagramByIdGetTest() throws ApiException {
        String id = null;
        api.processDefinitionDiagramByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionGetTest() throws ApiException {
        String accept = null;
        api.processDefinitionGet(accept);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionKeyPayTaxesStartPost
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionKeyStartByKeyPostTest() throws ApiException {
        String accept = null;
        String contentType = null;
        String key = null;
        Model1processDefinition1key17Bkey7D1startRequest body = null;
        api.processDefinitionKeyStartByKeyPost(accept, contentType, key, body);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionKeyPayTaxesStartFormGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionKeyStartFormByKeyGetTest() throws ApiException {
        String key = null;
        api.processDefinitionKeyStartFormByKeyGet(key);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionKeyPayTaxesXmlGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionKeyXmlByKeyGetTest() throws ApiException {
        String key = null;
        api.processDefinitionKeyXmlByKeyGet(key);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionPayTaxes50520118099b411e792b20242ac110002StartFormGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionStartFormByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processDefinitionStartFormByIdGet(accept, id);

        // TODO: test validations
    }
    
    /**
     * ProcessDefinitionPayTaxes50520118099b411e792b20242ac110002StatisticsGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processDefinitionStatisticsByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processDefinitionStatisticsByIdGet(accept, id);

        // TODO: test validations
    }
    
}
