/*
 * Camunda Rest API
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessInstanceApi
 */
@Ignore
public class ProcessInstanceApiTest {

    private final ProcessInstanceApi api = new ProcessInstanceApi();

    
    /**
     * ProcessInstance3fde771b9aed11e792b20242ac110002VariablesGet
     *
     * TODO: Add Description
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processInstanceVariablesByIdGetTest() throws ApiException {
        String accept = null;
        String id = null;
        api.processInstanceVariablesByIdGet(accept, id);

        // TODO: test validations
    }
    
}
